# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import main_pb2 as main__pb2


class AnswerSheetExtractorServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.extractAnswerSheet = channel.stream_unary(
                '/answer_sheet_extractor.AnswerSheetExtractorService/extractAnswerSheet',
                request_serializer=main__pb2.ExtractAnswerSheetRequest.SerializeToString,
                response_deserializer=main__pb2.ExtractAnswerSheetResponse.FromString,
                )


class AnswerSheetExtractorServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def extractAnswerSheet(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AnswerSheetExtractorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'extractAnswerSheet': grpc.stream_unary_rpc_method_handler(
                    servicer.extractAnswerSheet,
                    request_deserializer=main__pb2.ExtractAnswerSheetRequest.FromString,
                    response_serializer=main__pb2.ExtractAnswerSheetResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'answer_sheet_extractor.AnswerSheetExtractorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AnswerSheetExtractorService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def extractAnswerSheet(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/answer_sheet_extractor.AnswerSheetExtractorService/extractAnswerSheet',
            main__pb2.ExtractAnswerSheetRequest.SerializeToString,
            main__pb2.ExtractAnswerSheetResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
